version: "3.0"

networks:
  team09_network:
    name: team09_network
    external: true

services:
  zk1:
    container_name: zk1
    image: zookeeper:3.5
    networks:
      team09_network:
    restart: always
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "zk1_data:/data"

  zk2:
    container_name: zk2
    image: zookeeper:3.5
    networks:
      team09_network:
    restart: always
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "zk2_data:/data"

  zk3:
    container_name: zk3
    image: zookeeper:3.5
    networks:
      team09_network:
    restart: always
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - "zk3_data:/data"

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: docker.io/bitnami/kafka:latest
    networks:
      team09_network:
        ipv4_address: 172.9.0.10 
    restart: on-failure
    ports:
      - "19092:19092"
      - "19094:19094"
    volumes:
      - "kafka1_data:/kafka-data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:19092,EXTERNAL://:19094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://13.124.248.100:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: docker.io/bitnami/kafka:latest
    networks:
      team09_network:
        ipv4_address: 172.9.0.11    
    restart: on-failure
    ports:
      - "29092:29092"
      - "29094:29094"
    volumes:
      - "kafka2_data:/kafka-data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:29092,EXTERNAL://13.124.248.100:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka3:
    container_name: kafka3
    hostname: kafka3
    image: docker.io/bitnami/kafka:latest
    networks:
      team09_network:
        ipv4_address: 172.9.0.12
    restart: on-failure
    ports:
      - "39092:39092"
      - "39094:39094"
    volumes:
      - "kafka3_data:/kafka-data"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:39092,EXTERNAL://:39094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:39092,EXTERNAL://13.124.248.100:39094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    depends_on:
      - zk1
      - zk2
      - zk3

  zookeeper-navigator:
    hostname: zookeeper-navigator
    container_name: zookeeper-navigator
    image: elkozmon/zoonavigator:1.1.2
    networks:
      team09_network:
    restart: always
    ports:
      - 9000:9000
    environment:
      HTTP_PORT: 9000
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      team09_network:
    restart: on-failure
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092
        #- KAFKA_CLUSTERS_1_NAME=secondLocal
        #- KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka2:29092
        #- KAFKA_CLUSTERS_2_NAME=thirdLocal
        #- KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS=kafka3:39092
        #- SERVER_SERVLET_CONTEXT_PATH=/kafkaui
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=1234
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  zk1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./zk-volume/zk-1/data

  zk2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./zk-volume/zk-2/data

  zk3_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./zk-volume/zk-3/data

  kafka1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./kafka-volume/kafka1/data

  kafka2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./kafka-volume/kafka2/data

  kafka3_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./kafka-volume/kafka3/data
